### PR TITLE
Add a CHANGELOG.md

### PR DESCRIPTION
**Pull request by nimeshksingh**
I've filled in a bit of the changelog looking at commits since the previous release, but @austinlparker and @iredelmeier, you've
actually committed all of those changes, so please add / edit what I've put via comments and I'll incorporate.
(Alternatively feel free to push to the branch.)

### CODE REVIEW

**Review by iredelmeier — APPROVED** [review]

**Comment by iredelmeier** [comment]
LGTM. However, I'm not sure if we need fields that are unused , e.g., `Security`.

(This is something we should standardize...)

**Review by austinlparker — APPROVED** [review]

**Comment by austinlparker** [comment]
I don't mind having the unused fields in there since we're basing it off a standard (or at least a nice looking website which is like, what, 80-90% of making something official these days? 😂)

**Comment by nimeshksingh** [comment]
My thought was have the empty fields in the "Unreleased" section but remove any that are still empty once it becomes a real version.

**Comment by austinlparker** [comment]
Yeah, that makes sense.

**Pull request merged**
