### PR TITLE
Update to the latest version of OpenTracing gem and update dependencies.

### PR DESCRIPTION
**Pull request by josh-lauer**
Bump to the latest version of the OpenTracing gem.

### CODE REVIEW

**Comment by austinlparker** [comment]
Thanks for the PR! Does this include the change to `start_span`/`start_active_span` to include accepting a block?

**Comment by josh-lauer** [comment]
> Thanks for the PR! Does this include the change to `start_span`/`start_active_span` to include accepting a block?

Yes. We needed to bump it because the older version was missing the `start_active_span` method and some of the instrumentation libraries we are using depend on it.

Thanks for taking a look!

**Comment by austinlparker** [comment]
I guess I'm confused, then - I see that you updated the dependencies, but doesn't supporting the block return require updating the implementation as well? (https://github.com/lightstep/lightstep-tracer-ruby/blob/master/lib/lightstep/tracer.rb#L90)

**Comment by josh-lauer** [comment]
I'm sorry, I'm probably the one who is confused here. Are you saying that updating to `0.5.0` of the opentracing gem would require updates to the lightstep tracer?

**Comment by austinlparker** [comment]
That's my understanding, yes (which is, iirc, why we haven't updated it yet from what I've been told -- not really a rubyist, so I haven't had the time to dig in and see for myself)

**Comment by josh-lauer** [comment]
It seems you are correct, the newest version of the reference implementation of the opentracing tracer does indeed have different behavior. So, I made some updates to implement the changes between opentracing-ruby 0.4.x and 0.5.0, using this diff as a reference: https://github.com/opentracing/opentracing-ruby/compare/0db1fe2..01304d

Thanks for looking!

**Comment by austinlparker** [comment]
Thanks, changes look great. I'll see about getting a release out!

**Pull request merged**
